# Generated by Django 4.0.6 on 2022-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_manufacturer_manufacturers_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='book',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='porduct',
            field=models.ManyToManyField(blank=True, through='cart.ProductInOrder', to='store.cosmetics', verbose_name='Product'),
        ),
    ]
