# Generated by Django 4.0.6 on 2022-12-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='cosmetics',
        ),
    ]
